### ISSUE TITLE
rpc/rpc.pb.go: missing source [open source compliance]

### ISSUE THREAD

**Issue by onlyjob** [checkpoint-restore/go-criu#9]
[rpc/rpc.pb.go](../blob/master/rpc/rpc.pb.go) is a generated file but its source is missing...

Would it be possible to commit it to this repository please?

**Comment by rst0git** [comment]
Hi @onlyjob, the source file is in the CRIU's repository.
https://github.com/checkpoint-restore/criu/blob/criu-dev/images/rpc.proto

`rpc/rpc.pb.go` can be generated with:
```
make rpc/rpc.pb.go
```

**Comment by onlyjob** [comment]
The problem is that source release is not comprehensive. Downstream we can not download on build and another repository (with .proto file) is not available. Effectively it is partially an open source compliance problem (because generated file is shipped without sources - like pre-compiled binary) but also partially a technical problem because without source we can not ensure integrity of build by re-building all pre-generated files.

**Comment by adrianreber** [comment]
Hmm, this is difficult. We did not include the original file, because it is part of CRIU and we actually, in the go bindings, do not want that file in the repository. We only want the result from the protobuf compiler. The Makefile rule is just as a convenience to easy update the file if necessary.

I understand your point of view, but for us generating the file is not part of the build process. Another motivation to leave out the generation of the build process is to not require the protobuf compiler during build as well as to make sure that the generated file matches what we expect. I often had problems generating protobuf output because of different versions of the protobuf compiler.

**Comment by onlyjob** [comment]
This is precisely why source should be committed to this repository. Yes it would duplicate the original file but that is the only way to take care of situations where/when generated file should be updated from the source by the different compiler. Proper interoperability requires to re-build such files for consistency and sometimes it is just necessary to regenerate such files in order to avoid FTBFS due to mismatch between different .pb.go files produced by incompatible compiler versions.
Imagine what (chaos) will happen if all libraries bundle source-less pre-generated files produced by different compiler versions. This is precisely what we are trying to avoid and that's why it is _necessary_ to provide sources.  
I don't see much drama if that one `.proto` file will have to be updated from parent repository once in a while.

**Comment by kolyshkin** [comment]
Maybe there's a way to add criu as a git submodule? It won't be required to build, but in case someone wants to regenerate the protobuf files there will be a way to do it.

@onlyjob care to implement it?

**Comment by adrianreber** [comment]
Should be solved.
